### ISSUE TITLE
Build instructions inadequate

### ISSUE THREAD

**Issue by Sqeaky** [mo22/jnipp#3]
The closest I could get to building with gcc or clang is as follows: 

g++ -std=c++11 -fvisibility=hidden -fvisibility-inlines-hidden  test.cpp _java.cpp -o test -I .. -I /usr/lib/jvm/default-java/include -I .

I need the "-I" include the jni headers, but this will need to be adjusted per platform. Perhaps a build system, like cmake and find_package command could be used to facilitate this. Also, "_java.cpp" was not included and needs to be.

**Comment by mo22** [comment]
Hm, _java.cpp and _java.h should not be in the repository as they are automatically generated.

The "generate" script is supposed to create class structures for the classes listed, in the test example its only for the java.lang.String and JavaTest classes. But _java.cpp was missing in the Makefile as an output.

I needed to add -DJNIPP_USE_TYPE_TRAITS to make the example work - type traits are needed to specialize the Ref template classes for certain types (like creating a Ref<String> from const char*).

CMake would make a lot of sense, I'll do that when I find some time. Right now the test Makefile needs to be adapted to the local system (java paths, compiler settings)

I've added a Makefile.osx and Makefile.linux, which both work for me, but CMake would make more sense.

**Comment by Sqeaky** [comment]
I did leave that define out of my instructions, sorry I should have included that.

Interesting decision to leave a file that doesn't change out of the tests. That does mean that if someone has trouble with the generate script they cannot run the tests. Also, as near I could tell the bulk of this project would work on windows as well, but the generate script would not.

**Comment by mo22** [comment]
Hmm, I believe that automatically generated files should not be in the repo. The generate script is pretty much one ugly java class, and the bash script only calls java generate with some options (classpath etc.), for windows it would be straight forward to write a .bat or .cmd file.
