### ISSUE TITLE
Resolve return temporary todo

### ISSUE THREAD

**Issue by Sqeaky** [mo22/jnipp#4]
On line 299 there is a todo. This likely needs to beremoved. The commented code cannot work correctly, the destructor for std::string is allowed to (expected to?) free the memory that is pointed at by the return of string::c_str().

```
/*
    // @TODO: this is buggy.
    const char* c_str() const {
        std::string tmp = std_str();
        return tmp.c_str();
    }
*/
```

**Comment by mo22** [comment]
removed. true, returning a const char\* can never work.
