### ISSUE TITLE
Compilation warning using #elif JNIPP_USE_TYPE_TRAITS

### ISSUE THREAD

**Issue by Sqeaky** [mo22/jnipp#5]
Should be either an #else or an #elif defined. I have sample fixed for this at: https://github.com/Sqeaky/jnipp/blob/master/jnipp.h

**Comment by mo22** [comment]
fixed.

**Comment by Sqeaky** [comment]
Thanks for fixing all these things. Was this the right way to let you know?

I don't want to seem demanding, I just figured you could use the results of me looking at your code.

**Comment by mo22** [comment]
It's perfect ;) As you might have guessed I'm using this only for an android project so it's pretty focused on osx / clang / android, but there is no reason it wouldn't work on any other jni platform.
